hugover: extended_0.115.2
serve:
  - key: default
    config: config.yaml
build:
  - key: default
    config: config.yaml
menu:
  - key: settings
    title: Settings
    menuItems:
      - key: mainConfig
  - title: Ressources
    menuItems:
      - key: personnes
      - key: organisations
      - key: liste_organisations
      - key: choix_orga
  - title: Posts
    menuItems:
      - key: posts
singles:
  - key: mainConfig
    title: Site Configuration
    file: config.yaml
    fields:
      - key: title
        title: Site Title
        type: string
        tip: Your page title.
      - key: baseURL
        title: Base URL
        type: string
        tip: Your site URL.
  - key: liste_organisations
    title: Liste Organisations
    file: quiqr/model/partials/liste_organisations.yaml
    fields:
      - field:
          key: some_child_field
          title: Nom organisation
          type: string
        key: options
        title: Options
        type: leaf-array
  - key: choix_orga
    title: Choix orga
    file: choix.md
    fields:
    - key: select-from-query
      multiple: false
      query_glob: quiqr/model/partials/liste_organisations.yaml
      query_string: .options[]
      type: select-from-query